title: Claes Redestad's blog
author: cl4es
email: claes.redestad@gmail.com
description:
  A blog about Java, OpenJDK and various performance related adventures thereabout.

# social links
twitter_username: cl4es
github_username:  cl4es

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
        date_format: "%Y-%m-%d %H:%M"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
